[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
liberfi_pm = "5oBHzLgzE3X8QKQDspH2gCN34g1tbhnKs9dXxQ8KM8Sk"

[programs.localnet]
liberfi_pm = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
